version: '3'
# This was untested in docker, your rootpassword may need changed
# and the image may need to be changed in order to get the application running in docker.

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      #root password may need changed depending on your enviorment
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=rental_property_app
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    volumes:
      - /data/mysql
  # spring-boot-jpa-app:
  #   image: spring-boot-jpa-image
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mysql-docker-container
  #   ports:
  #     - 8087:8080
  #   volumes:
  #     - /data/spring-boot-app
